# This playbook is for default provisioning of my vagrant boxes, so that
# I always have a familiar environment with necessary tools installed
# when I work on them.  I have a global Vagrantfile in ~/.vagrant.d/
# which assigns this playbook to all boxes.

- hosts: all
  pre_tasks:
    - name: install common apt packages
      apt:
        name: "{{ item }}"
        state: present
        install_recommends: no
        update_cache: yes
        cache_valid_time: 36000
      with_items:
        - git
        - ranger
        - trash-cli
      become: yes

  roles:
    - dotfiles
