  # Ansible from official repos is ancient - use PPA
- name: add ansible PPA
  command: >
    add-apt-repository --yes ppa:ansible/ansible
    creates=/etc/apt/sources.list.d/ansible-ansible-trusty.list
  register: ansible_ppa_status
  become: yes

- name: update apt cache
  apt: update_cache=yes
  when: ansible_ppa_status.changed == true
  become: yes

- name: install latest Ansible
  apt: name=ansible state=latest
  become: yes

- name: create directory for roles from ansible galaxy
  file: path=/etc/ansible/roles state=directory
  become: yes

- name: check for blockinfile role
  shell: ansible-galaxy list | grep yaegashi.blockinfile
  register: blockinfile_check
  changed_when: false
  failed_when: blockinfile_check.rc > 1

- name: install blockinfile role
  shell: ansible-galaxy install yaegashi.blockinfile
  when: blockinfile_check.rc == 1
  become: yes

- name: create directory for ansible plugins
  file: path=/usr/share/ansible_plugins/{{ item }} state=directory
  with_items:
    - callback_plugins
    - vars_plugins
    - lookup_plugins
  become: yes

- name: download ansible-profile plugin
  # I don't use get_url module because it's slower.
  command: >
    wget https://raw.githubusercontent.com/jlafon/ansible-profile/master/callback_plugins/profile_tasks.py
    chdir=/usr/share/ansible_plugins/callback_plugins/
    creates=/usr/share/ansible_plugins/callback_plugins/profile_tasks.py
  become: yes
  
- name: install passwordstore plugin
  copy:
    src: passwordstore.py
    dest: /usr/share/ansible_plugins/lookup_plugins/passwordstore.py
  become: yes

- name: clone ansible-system-setup repository
  git: 
    repo=https://github.com/janek-warchol/ansible-system-setup/
    dest=~/.config/ansible-system-setup/
    version=devel
  register: task_result
  failed_when: task_result | failed and "Local modifications exist in repository" not in task_result.msg

- name: update ansible-system-setup remote
  lineinfile:
    dest: ~/.config/ansible-system-setup/.git/config
    regexp: url = .*ansible-system-setup
    line: "	url = {{ this_repo_remote }}"

  # I don't want to accidentally commit something with my work email.
- name: override git authorship setting in ansible-system-setup
  blockinfile:
    dest: ~/.config/ansible-system-setup/.git/config
    block: |
      [user]
      	name = Jan Warchoł
      	email = jan.warchol@gmail.com
  # don't use "inventory_hostname in groups.xxx" construct
  # because it fails when group xxx is not defined.  This is better.
  when: "'work_computers' in group_names"
