- name: Add Google Chrome APT key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub
  become: yes

- name: add Google Chrome APT repository
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main'
  become: yes

- name: install Google Chrome
  apt:
    name: google-chrome-stable
    state: latest
  become: yes
