# FIXME
# Ansible's apt_repository module doesn't work correcty with Linux Mint,
# see https://github.com/ansible/ansible/issues/4587
# Also, the filenames that are checked for existence are hardcoded :(

- name: Add official git PPA
  command: >
    add-apt-repository --yes ppa:git-core/ppa
    creates=/etc/apt/sources.list.d/git-core-ppa-trusty.list
  register: git_ppa_status
  become: yes

- name: Add FreeFileSync PPA
  command: >
    add-apt-repository --yes ppa:freefilesync/ffs
    creates=/etc/apt/sources.list.d/freefilesync-ffs-trusty.list
  register: ffs_ppa_status
  become: yes

#- name: FreeFileSync wasn't available in Utopic Unicorn repos
#  shell: sed -i 's/utopic/trusty/' /etc/apt/sources.list.d/freefilesync*
#  become: yes

- name: update apt cache
  apt: update_cache=yes
  when: git_ppa_status.changed or ffs_ppa_status.changed
  become: yes

- name: Install latest versions of apt packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - baobab
    - build-essential
    - dconf-cli
    - dconf-editor   # desktop environment configuration
    - firefox   # make sure firefox is updated - my package manager
                # didn't want to update it on its own
    - flip
    - freefilesync
    - git
    - gitk
    - gparted
    - htop
    - indicator-multiload
    - ipython
    - gnupg
    - kate
    - keepass2
    - xdotool   # library for auto-type in keepass
    - libdvdread4   # DVD decryption
      # at least one of these 3 packages is needed for okular to open pdfs
    - kdelibs5-plugins
    - kdelibs5-data
    - oxygen-icon-theme
    - okular
    - openjdk-7-jre
    - openssh-server
    - pass
    - python-pip
    - python-dev
    - python-virtualenv
    - python-numpy
    - python-scipy
    - python-matplotlib
    - python-tk
    - ranger
    - sshfs
    - terminator
    - tmux
    - trash-cli
    - tree
    - vim
    - vim-gnome
    - vlc
    - xbacklight   # changing screen brightness
    - xsel   # copying and pasting from middle-mouse-button clipboard
    #- gimp
    #- guake
    #- imagemagick
    #- kompare
  become: yes

# TODO
# I think this is not needed anymore...
#- name: Finish DVD decryption installation
#  shell: /usr/share/doc/libdvdread4/install-css.sh
#  become: yes

